version: "2"

run:
  timeout: 5m
  go: '1.26'

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
  exclusions:
    generated: lax
    paths:
      - api

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
